#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           motorA,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_drive,   tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_drive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C2_1,    placer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    goal_grab,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____             _
|  __ \          (_)
| |  | | ___  ___ _  __ _ _ __   ___  ___  __ _ _   _ _ __ ___
| |  | |/ _ \/ __| |/ _` | '_ \ / _ \/ __|/ _` | | | | '__/ __|
| |__| |  __/\__ \ | (_| | | | | (_) \__ \ (_| | |_| | |  \__ \
|_____/ \___||___/_|\__, |_| |_|\___/|___/\__,_|\__,_|_|  |___/
__/ |
|___/                            Team #6369
Judge Demo Program: 2014-2015 (Cascade Effect)
*/

#include "JoystickDriver.c"
#include "a_globals.h"
#include "..\common\bot_specific.h"
#include "..\common\init.h"
#include "..\common\functions.h"
#include "..\common\servo.h"
#include "..\sensor\drivers\hitechnic-irseeker-v2.h"
#include "..\sensor\GetIR.h"
#include "..\sensor\ultrasonic.h"
#include "..\common\macros.h"
#include "..\common\UpdateLiftEncoderTask.h"
#include "..\common\UpdateDisplayTask.h"
#include "..\common\UpdateDriveBearings.h"
#include "..\common\HarvesterTask.h"
#include "drive.h"
#include "sonar.h"


// Usage: start from the center of the parking zone.
// Go for a fixed distance.  Then  you know if the range is:
// Low - the skinnny end is pointed toward you.  Typical dist is 51
// Mid - the flat end is pointed toward you.  Typ dist is 68
// Hi (no reading => 255) the goal is at 45.
int getGoalState() {
	int range = getClosestRange();
	writeDebugStreamLine("%d", range);
	if(range < 65) {
		// |
		return 1;
		} else if(range < 100) {
		// -
		return 2;
		} else {
		// /
		return 3;
	}
}

void knockKickstand() {
	wait1Msec(500);
	pivotDegrees(70, 50);
	goForwardDistance(1.7, 60);
	pivotDegrees(-75, 50);
	goForwardDistance(2, 100);
	goForwardDistance(.5, 50);
}

void placeInCenter() {
	goToRange(49, 30);
	angle_before_ir = total_angle;
	if (PointToIR() == false) stopAndWait();
	TossToCenterGoal();
	//liftToCenterGoal();
	//wait1Msec(500);
	//stopAndWait();
	//liftPlace();
	//wait1Msec(500);
	//stopAndWait();
	liftToFloor();
	//pivotToTotalAngle(angle_before_ir, 40);
	//stopAndWait();
}

task main() {
	initDisplay();
	goalGrabberUp();
	initPlacer();
	initDriveConfig();

	// 	Initial position for cup is tilted a little up, so we do not lose
	// The small balls.
	servo[wrist] = 100;
	wristPos = (float) 100;
	servo[elbow] = 240;
	elbowPos = 240;
	waitForStart();

	eraseDisplay();
	StartTask(UpdateLiftEncoderTask);
	//StartTask(HarvesterTask);  If you start this total_angle goes wrong.
	StartTask(UpdateDriveBearingsTask);
	StartTask(UpdateDisplayTask);

	goForwardDistance(2, 30);
	stop();
	//stopAndWait();
	switch(getGoalState()) {
	case 1:  // Skinny side facing us
		placeInCenter();
		break;
	case 2: //---  Flat side facing us
		PlaySound(soundFastUpwardTones);
		pivotDegrees(-60, 50);
		goForwardDistance(4, 50);
		pivotToTotalAngle(0, 50);
		goForwardDistance(0.2, 40);
		pivotToTotalAngle(95, 50);
		if (PointToIR() == false) stopAndWait();
		//stopAndWait();
		placeInCenter();
		break;
	case 3:  /// / Angled goal
		PlaySound(soundException);
		pivotDegrees(-80, 50);
		goForwardDistance(1.6, 50);


		pivotToTotalAngle(45, 50);
		//stopAndWait();
		if (PointToIR() == false) stopAndWait();
		//stopAndWait();
		placeInCenter();
		//stopAndWait();
		break;
	}
	knockKickstand();
	stopAndWait();
}
