#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_drive,   tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_drive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    placer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    goal_grab,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

_____             _
|  __ \          (_)
| |  | | ___  ___ _  __ _ _ __   ___  ___  __ _ _   _ _ __ ___
| |  | |/ _ \/ __| |/ _` | '_ \ / _ \/ __|/ _` | | | | '__/ __|
| |__| |  __/\__ \ | (_| | | | | (_) \__ \ (_| | |_| | |  \__ \
|_____/ \___||___/_|\__, |_| |_|\___/|___/\__,_|\__,_|_|  |___/
					 __/ |
					|___/                            Team #6369
Autonomous Code: 2014-2015 (Cascade Effect)
*/

#include "JoystickDriver.c"
#include "a_globals.h"
#include "..\common\bot_specific.h"
#include "..\common\init.h"
#include "..\common\functions.h"
#include "..\common\servo.h"
#include "drive.h"
#include "sonar.h"
#include "..\sensor\ultrasonic.h"
#include "..\common\UpdateLiftEncoderTask.h"
#include "..\common\UpdateDriveBearings.h"
#include "..\common\UpdateDisplayTask.h"
//#include "FromParking.h"
//#include "IfBlocked.h"

bool haveGoal = false;
void checkForGoal(){
    if (SensorValue[ultrasonic] < 30) {
        haveGoal = true;
        PlaySound(soundUpwardTones);
    }
}

void GoalFromRamp(){
    float angle_before_goal = 0;

    // Starting from top of ramp, go place the ball in the goal.
    goForwardDistance(4.7, 40);
    DetectObstacles = 20;
    if(goForwardDistance(1, 50)) {
        // Blocked, so just stop, rather than risk damage.
        PlaySound(soundDownwardTones);
        stopAndWait();
    }
    DetectObstacles = 0;
    goToRange(28, 40);
    stop();
    // stopAndWait();
    // Record the angle before we find the goal
    angle_before_goal = total_angle;
        GoalPlacer();
    //pivotDegrees(-3, 80); // Compensate for hardware being slightly off center
    jogForwardCm(17, 10);
    stop();
    goalGrabberDown();
    wait1Msec(1000);
    // Now go back to that angle
    pivotToTotalAngle(angle_before_goal, 40);

    // GO PARK THE TUBE
    BackwardsArcToAngle(50, 0.3, 50);
    checkForGoal();
    goBackwardDistance(1.8, 70);
    checkForGoal();
    BackwardsArcToAngle(50, 0.3, -5); // 5 degrees aims us at wall.
    checkForGoal();
    if (haveGoal == false) stopAndWait();
    goBackwardDistance(4.2, 70);
    pivotToTotalAngle(-100, 50); // Place in parking zone.
    ResetTrip();
    //goForwardDistance(0.5, 40);
    StopAndDone();
}

task main() {
    initDisplay();
    goalGrabberUp();
    initPlacer();
    initElbow();
    initWrist();
    initDriveConfig();

    waitForStart();
    eraseDisplay();
    StartTask(UpdateLiftEncoderTask);
    StartTask(UpdateDisplayTask);
    StartTask(UpdateDriveBearingsTask);

    GoalFromRamp();
}
