#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,    ultrasonic,               sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_drive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     left_drive,   	tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C2_1,    placer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    goal_grab,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____             _
|  __ \          (_)
| |  | | ___  ___ _  __ _ _ __   ___  ___  __ _ _   _ _ __ ___
| |  | |/ _ \/ __| |/ _` | '_ \ / _ \/ __|/ _` | | | | '__/ __|
| |__| |  __/\__ \ | (_| | | | | (_) \__ \ (_| | |_| | |  \__ \
|_____/ \___||___/_|\__, |_| |_|\___/|___/\__,_|\__,_|_|  |___/
					 __/ |
					|___/                            Team #6369
Autonomous Code: 2014-2015 (Cascade Effect)
*/

#include "JoystickDriver.c"
#include "a_globals.h"
#include "..\common\functions.h"
#include "..\common\servo.h"
#include "..\common\macros.h"
#include "..\common\UpdateLiftEncoderTask.h"
#include "..\common\UpdateDriveBearings.h"
#include "..\sensor\ultrasonic.h"
#include "UpdateDisplayTask.h"
#include "drive.h"

int getGoalState() {
	int range = getClosestRange();
	writeDebugStreamLine("%d", range);
	if(range < 62) {
		// -
		return 1;
	} else if(range < 80) {
		// |
	   return 2;
	} else {
		// /
		pivotToTotalAngle(8, 80);
		int range2 = getClosestRange();
		pivotToTotalAngle(-8, 80);
		int range3 = getClosestRange();
		pivotToTotalAngle(0, 80);
		if(range2 == 255 && range3 == 255) {
			return 3;
		} else {
			if(range2 < 62 && range3 < 62) return 1;
			if(range2 < 80 && range3 < 80) return 2;
			return 2;
		}
	}
}

task main() {
	goalGrabberUp();
	placerDown();

	//waitForStart();
	eraseDisplay();
	StartTask(UpdateLiftEncoderTask);
	StartTask(UpdateDisplayTask);
	StartTask(UpdateDriveBearingsTask);

    goForwardDistance(2, 80);
	int state = getGoalState();
	switch(state) {
		case 1:
            goForwardDistance(4.5, 80);
        break;
        case 2:
            goForwardDistance(4, 80);
            pivotToTotalAngle(90, 60);
            goForwardDistance(2, 80);
            pivotToTotalAngle(0, 60);
            goForwardDistance(1, 80);
            pivotToTotalAngle(-90, 60);
        break;
        case 3:
            goForwardDistance(2, 80);
        break;
	}
	stopAndWait();
}
