#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     HTIRS2,              sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           motorA,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_drive,   tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_drive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C2_1,    placer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    goal_grab,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____             _
|  __ \          (_)
| |  | | ___  ___ _  __ _ _ __   ___  ___  __ _ _   _ _ __ ___
| |  | |/ _ \/ __| |/ _` | '_ \ / _ \/ __|/ _` | | | | '__/ __|
| |__| |  __/\__ \ | (_| | | | | (_) \__ \ (_| | |_| | |  \__ \
|_____/ \___||___/_|\__, |_| |_|\___/|___/\__,_|\__,_|_|  |___/
					 __/ |
					|___/                            Team #6369
Judge Demo Program: 2014-2015 (Cascade Effect)
*/

#include "JoystickDriver.c"
#include "a_globals.h"
#include "..\common\bot_specific.h"
#include "..\common\init.h"
#include "..\common\functions.h"
#include "..\common\servo.h"
#include "..\sensor\drivers\hitechnic-irseeker-v2.h"
#include "..\sensor\GetIR.h"
#include "..\sensor\ultrasonic.h"
#include "..\common\macros.h"
#include "..\common\UpdateLiftEncoderTask.h"
#include "..\common\UpdateDisplayTask.h"
#include "..\common\UpdateDriveBearings.h"
#include "..\common\HarvesterTask.h"
#include "drive.h"
#include "sonar.h"

int getGoalState() {
    int range = getClosestRange();
    writeDebugStreamLine("%d", range);
    if(range < 65) {
        // |
        return 1;
    } else if(range < 100) {
        // -
        return 2;
    } else {
        // /
        return 3;
    }
}

void knockKickstand() {
    wait1Msec(500);
    pivotDegrees(45, 40);
    goForwardDistance(1.5, 60);
    pivotDegrees(-55, 40);
    goForwardDistance(3.0, 100);
}

void placeInCenter() {
    goToRange(46, 40);
    angle_before_ir = total_angle;
    // stopAndWait();
    PointToIR();
    liftToCenterGoal();
    wait1Msec(1000);
    liftPlace();
    wait1Msec(1000);
    // stopAndWait();
    liftToFloor();
    pivotToTotalAngle(angle_before_ir, 40);
    // stopAndWait();
}

task main() {
    initDisplay();
    goalGrabberUp();
    initPlacer();
    initElbow();
    initWrist();
    initDriveConfig();

    eraseDisplay();
    StartTask(UpdateLiftEncoderTask);
    StartTask(HarvesterTask);
    StartTask(UpdateDriveBearingsTask);
    StartTask(UpdateDisplayTask);

    goForwardDistance(2, 30);
    switch(getGoalState()) {
        case 1:
            placeInCenter();
            break;
        case 2:
						PlaySound(soundBeepBeep);
						pivotDegrees(-60, 40);
						goForwardDistance(4, 40);
						pivotToTotalAngle(0, 40);
						goForwardDistance(0.5, 40);
						pivotToTotalAngle(95, 40);
						PointToIR();
						placeInCenter();
        break;
        case 3:
						PlaySound(soundException);
						pivotDegrees(-70, 40);
						goForwardDistance(2.3, 40);
						pivotToTotalAngle(45, 40);
						PointToIR();
						placeInCenter();
        break;
    }
    knockKickstand();
}
