#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     right_drive,   tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left_drive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    placer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    goal_grab,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____             _
|  __ \          (_)
| |  | | ___  ___ _  __ _ _ __   ___  ___  __ _ _   _ _ __ ___
| |  | |/ _ \/ __| |/ _` | '_ \ / _ \/ __|/ _` | | | | '__/ __|
| |__| |  __/\__ \ | (_| | | | | (_) \__ \ (_| | |_| | |  \__ \
|_____/ \___||___/_|\__, |_| |_|\___/|___/\__,_|\__,_|_|  |___/
					 __/ |
					|___/                            Team #6369
Autonomous Code: 2014-2015 (Cascade Effect)
*/

#include "JoystickDriver.c"
#include "a_globals.h"
#include "..\common\init.h"
#include "..\common\functions.h"
#include "..\common\servo.h"
#include "..\common\macros.h"
#include "..\common\UpdateLiftEncoderTask.h"
#include "..\common\UpdateDriveBearings.h"
#include "..\sensor\ultrasonic.h"
#include "..\common\UpdateDisplayTask.h"
#include "drive.h"

void KickstandGetter() {
    int i;
    for(i = 0; i < 11; i++) {
        motor[left_drive] = 100;
        motor[right_drive] = -20 + 4 * i;
        wait1Msec(1000);
    }
}

void rampKickstand(){
    /*
     * Go for the kickstand.
     * Assumes at the bottom of the ramp, back wheels just onto the field
     * Start at the center.
     */

    goForwardDistance(0.3, 80);
    pivotDegrees(-75, 60); //  Turn NW
    int range = 255;
    wait10Msec(50);
    range = getClosestRange();

    writeDebugStreamLine("range: %d", range);

    if(range < 105) {
        // it's 3. Skinny end of center goal is toward us. Kickstand on right.
        PlaySound(soundFastUpwardTones);
        pivotDegrees(30, 60);
        goForwardDistance(2, 100);
        pivotDegrees(-10, 60);
        goForwardDistance(2, 100);
        KickstandGetter();
    } else if(range < 130) {
        // it's 1. Flat part of goal is toward us.
        PlaySound(soundDownwardTones);
        pivotDegrees(10, 60);
        goForwardDistance(2.8, 100);
        pivotDegrees(-90, 70);
        goForwardDistance(1.5, 100);
        KickstandGetter();
    } else {
        // it's 2, angled at 45 degrees to us.
        PlaySound(soundBlip);
        goForwardDistance(1.5, 100); // Drive towards kickstand.
        pivotDegrees(-45, 70);
        goForwardDistance(1, 100);
        pivotDegrees(90, 70);
        int range = 255;
        range = getClosestRange();
        goBackwardDistance(0.5, 80);
        pivotDegrees(40, 80);
        goForwardDistance(1, 80);
        pivotDegrees(-30, 80);
        goForwardDistance(2, 80);
        goBackwardDistance(1, 80);
        pivotDegrees(-45, 80);
        goForwardDistance(2.5, 80);
    }

    stopAndWait();
}

task main() {
    initDisplay();
    goalGrabberUp();
    placerDown();
    initElbow();
    initWrist();
    initDriveConfig();

    waitForStart();
    eraseDisplay();
    StartTask(UpdateLiftEncoderTask);
    StartTask(UpdateDisplayTask);
    StartTask(UpdateDriveBearingsTask);

    rampKickstand();
}
