float elbowPos;
float wristPos;
float lift_inches;
bool liftStopped;
const int DEADBAND = 12;
int drivePower = 100;
int pwrLift;
const int GUNNER_DEADBAND = 30;
bool running_macro = false;
bool override_macro = false;